version: "2"

services:
  debug:
    image: tjenwellens/tomcat
    command: /bin/sh -c "catalina.sh jpda start ; tail -F -n0 /etc/hosts"
    volumes:
      - ./target/SpringMvcjQueryJspDocker-1.0.0-BUILD-SNAPSHOT:/usr/local/tomcat/webapps/SpringMvcjQueryJspDocker
    environment:
      - JPDA_ADDRESS="1043"
    ports:
      - "8080:8080"
      - "1043:1043"
